In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("spiral.csv")
df.head()

x1        x2  y
0  0.000000  0.000000  0
1 -0.000650  0.010080  0
2  0.009809  0.017661  0
3  0.007487  0.029364  0
4 -0.000027  0.040404  0

In [4]:
X = df.drop('y', axis=1).to_numpy()

In [8]:
X[:10]

array([[ 0.00000000e+00,  0.00000000e+00],
       [-6.50123964e-04,  1.00800667e-02],
       [ 9.80910862e-03,  1.76607760e-02],
       [ 7.48711824e-03,  2.93635268e-02],
       [-2.71404625e-05,  4.04040313e-02],
       [ 7.41008855e-03,  4.99584899e-02],
       [ 3.04241080e-02,  5.24162974e-02],
       [ 2.47420249e-02,  6.62368632e-02],
       [ 1.60027032e-02,  7.92076979e-02],
       [ 3.90523417e-02,  8.20937112e-02]])

In [9]:
y = df['y'].to_numpy()

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [11]:
X.shape, y.shape

((300, 2), (300,))

In [15]:
d = X.shape[1]
h = 4
n = len(np.unique(y))

In [16]:
W1 = 0.01 * np.random.randn(d,h)
b1 = np.zeros((1,h))
W2 = 0.01 * np.random.randn(h,n)
b2 = np.zeros((1,n))

In [17]:
W1.shape, b1.shape

((2, 4), (1, 4))

In [18]:
W2.shape, b2.shape

((4, 3), (1, 3))

### Layer-1

In [19]:
Z1 = np.dot(X, W1) + b1        # (300,2) x (2,4) + (1,4) => (300,4)
Z1

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 6.57618897e-05,  2.32072808e-05, -5.77966203e-05,
        -1.15760347e-04],
       [ 1.99602195e-05, -8.39865376e-05, -1.33920602e-04,
        -1.71264473e-04],
       ...,
       [ 9.96317837e-03,  8.36891629e-03, -2.55218232e-03,
        -1.02809868e-02],
       [ 9.83454317e-03,  7.87249518e-03, -3.01574247e-03,
        -1.07290231e-02],
       [ 9.38699747e-03,  6.80113948e-03, -3.79016446e-03,
        -1.13071512e-02]])

In [20]:
Z1.shape

(300, 4)

In [23]:
# ReLU Activation --> if Z1 <= 0 then 0 else Z1
Z1[Z1<=0] = 0
A1 = Z1

In [24]:
A1

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.57618897e-05, 2.32072808e-05, 0.00000000e+00, 0.00000000e+00],
       [1.99602195e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.96317837e-03, 8.36891629e-03, 0.00000000e+00, 0.00000000e+00],
       [9.83454317e-03, 7.87249518e-03, 0.00000000e+00, 0.00000000e+00],
       [9.38699747e-03, 6.80113948e-03, 0.00000000e+00, 0.00000000e+00]])

In [25]:
A1.shape

(300, 4)

### Layer-2

In [27]:
Z2 = np.dot(A1, W2) + b2     # (300,4) x (4,3) + (1,3) = (300,3)
Z2[:10]

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.56109712e-07,  1.08739240e-06,  1.63410506e-06],
       [-2.20974266e-07,  2.21325526e-07,  3.46543128e-07],
       [-1.21716539e-06,  1.21910019e-06,  1.90882092e-06],
       [-2.47248351e-06,  3.65664956e-06,  5.53755369e-06],
       [-2.58410850e-06,  2.58821619e-06,  4.05253092e-06],
       [-5.29543336e-07,  5.30385097e-07,  8.30456903e-07],
       [-1.98919537e-06,  1.99235738e-06,  3.11955776e-06],
       [-3.68724118e-06,  3.69310240e-06,  5.78251992e-06],
       [-1.65751193e-06,  1.66014671e-06,  2.59939486e-06]])

In [28]:
Z2.shape

(300, 3)

In [29]:
# Applying Softmax for multiclass classification
exp_z2 = np.exp(Z2)
A2 = exp_z2/np.sum(exp_z2, axis=1, keepdims=True)
probs = A2

In [31]:
probs[:10]

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333289, 0.33333347, 0.33333365],
       [0.33333322, 0.33333337, 0.33333341],
       [0.33333272, 0.33333353, 0.33333376],
       [0.33333176, 0.33333381, 0.33333443],
       [0.33333202, 0.33333375, 0.33333423],
       [0.33333306, 0.33333342, 0.33333352],
       [0.33333232, 0.33333365, 0.33333403],
       [0.33333146, 0.33333392, 0.33333462],
       [0.33333249, 0.3333336 , 0.33333391]])

Calculating dz2

In [32]:
m = X.shape[0]

In [34]:
dz2 = probs
dz2[range(m),y] -= 1

In [35]:
dW2 = np.dot(A1.T, dz2)/m
dW2

array([[ 4.87147728e-04, -3.35578350e-05, -4.53589893e-04],
       [ 3.87254749e-04,  2.36680168e-04, -6.23934917e-04],
       [-2.38913959e-04,  3.57027355e-04, -1.18113395e-04],
       [-6.49695633e-04,  5.62275107e-04,  8.74205259e-05]])

In [40]:
db2 = np.sum(dz2, axis=0, keepdims=True)/m
db2

array([[-1.84912165e-05,  4.78165715e-06,  1.37095593e-05]])

In [41]:
dA1 = np.dot(dz2, W2.T)
dA1

array([[ 0.01686383,  0.01015091,  0.00157527,  0.00348852],
       [ 0.01686384,  0.01015092,  0.00157527,  0.00348852],
       [ 0.01686383,  0.01015091,  0.00157527,  0.00348852],
       ...,
       [-0.01156634, -0.00796464, -0.00093453, -0.0030653 ],
       [-0.01156641, -0.00796468, -0.00093454, -0.00306531],
       [-0.01156657, -0.00796478, -0.00093455, -0.00306535]])

In [42]:
dA1[Z1 <= 0] = 0 # was dA1[A1 <= 0] = 0. changed it to dA1[Z1 <= 0] = 0
dz1 = dA1 # same shape as dA1 (300, 4)

In [43]:
dW1 = np.dot(X.T, dz1)/m # (2, 300) x (300 ,4) => (2, 4)
db1 = np.sum(dz1, axis=0, keepdims=True)/m

In [45]:
lr = 0.1

In [46]:
# perform a parameter update
W1 += -lr * dW1
b1 += -lr * db1
W2 += -lr * dW2
b2 += -lr * db2